plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 3
